# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7c6fdb2b4f2618eb3b8f06406b9384cd8a363e7dead08470530e2a808af25e857211ba311d17dbab541b73a9526035d556d7ae7b9c18cbd369600def448e6c8

test:
  secret_key_base: 02138d7d8f8067e1c06819d7585d05f5503730241913e1a130e58634ba4cf09b60cfecf0428641ee816ea017650b4b415e356134dd62d1a51efc1b57cbd8c489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
